version: '3.5'

services:
  dummy-file-logs-1:
    image: test-dummy-file-logs:latest
    container_name: test-dummy-file-logs-1
    volumes:
      - ./dhv/logs/test-dummy-file-logs-1:/var/log/app
    command: |
      dummy-file-logs-1 -l /var/log/app/app.log -i 0.1
    networks:
      - raven_network

  dummy-file-logs-2:
    image: test-dummy-file-logs:latest
    container_name: test-dummy-file-logs-2
    volumes:
      - ./dhv/logs/test-dummy-file-logs-2:/var/log/app
    command: |
      dummy-file-logs-2 -l /var/log/app/app.log -i 0.1
    networks:
      - raven_network

  dummy-json-file-logs-1:
    image: test-dummy-json-file-logs:latest
    container_name: test-dummy-json-file-logs-1
    volumes:
      - ./dhv/logs/test-dummy-json-file-logs-1:/var/log/app
    command: |
      dummy-json-file-logs-1 -l /var/log/app/app.log -i 0.1
    networks:
      - raven_network

  dummy-json-stream-logs:
    image: test-dummy-json-stream-logs:latest
    container_name: test-dummy-json-stream-logs
    command: |
      dummy-json-stream-logs -i 0.1
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: dummy-logs.json
    networks:
      - raven_network


networks:
  raven_network:
    external: true

